spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test-db
    username: test
    password: test@123
    pool:
      enabled: true
      initial-size: 10
      maxSize: 30
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-main.yaml
    url: jdbc:postgresql://localhost:5432/test-db
    user: test
    password: test@123
